from datetime import datetime
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

class Condominio(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(200), nullable=False)
    cnpj = db.Column(db.String(18), nullable=False)
    tipo = db.Column(db.String(50))
    unidades = db.Column(db.Integer)
    cep = db.Column(db.String(9))
    endereco = db.Column(db.String(200))
    cidade = db.Column(db.String(100))
    estado = db.Column(db.String(2))
    contato_nome = db.Column(db.String(100))
    email = db.Column(db.String(100))
    telefone = db.Column(db.String(20))
    whatsapp = db.Column(db.String(20))
    nivel = db.Column(db.String(50))
    objetivo = db.Column(db.Text)
    observacoes = db.Column(db.Text)
    progress = db.Column(db.Integer, default=0)
    pdf_filename = db.Column(db.String(300))
    status = db.Column(db.String(20), default="pendente")
    email_verified = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)

class Empresa(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    nome = db.Column(db.String(200), nullable=False)
    cnpj = db.Column(db.String(18), nullable=False)
    categorias = db.Column(db.Text)
    descricao = db.Column(db.Text)
    cidade = db.Column(db.String(100))
    estado = db.Column(db.String(2))
    cep = db.Column(db.String(9))
    endereco = db.Column(db.String(200))
    telefone = db.Column(db.String(20))
    email_comercial = db.Column(db.String(100))
    website = db.Column(db.String(200))
    doc_filename = db.Column(db.String(300))
    status = db.Column(db.String(20), default="pendente")
    email_verified = db.Column(db.Boolean, default=False)
    created_at = db.Column(db.DateTime, default=datetime.utcnow)