"""empty message

Revision ID: 0548292158b4
Revises: 6e430cf87b20
Create Date: 2025-11-30 15:23:42.326228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0548292158b4'
down_revision = '6e430cf87b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    user_status = sa.Enum('ATIVO', 'SUSPENSO', 'PENDENTE', name='user_status')
    user_status.create(op.get_bind())
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ATIVO', 'SUSPENSO', 'PENDENTE', name='user_status'),
               existing_nullable=True)

    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('ATIVO', 'SUSPENSO', 'PENDENTE', name='user_status'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('empresa', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ATIVO', 'SUSPENSO', 'PENDENTE', name='user_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('ATIVO', 'SUSPENSO', 'PENDENTE', name='user_status'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    user_status = sa.Enum('ATIVO', 'SUSPENSO', 'PENDENTE', name='user_status')
    user_status.drop(op.get_bind())
    # ### end Alembic commands ###
