"""Adiciona campo is_active para suspender usuarios

Revision ID: 2a571f5ee52c
Revises: 0548292158b4
Create Date: 2025-11-30 22:03:03.498849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a571f5ee52c'
down_revision = '0548292158b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('condominio', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    op.add_column('empresa', sa.Column('is_active', sa.Boolean(), server_default=sa.true(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('empresa', 'is_active')
    op.drop_column('condominio', 'is_active')
    # ### end Alembic commands ###
