"""Remove subscription_status column from condominio

Revision ID: 3a3e3e4a2e8e
Revises: 2a571f5ee52c
Create Date: 2026-01-28 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a3e3e4a2e8e'
down_revision = '2a571f5ee52c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.drop_column('subscription_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('condominio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subscription_status', sa.VARCHAR(length=20), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
